import React, { useState } from 'react';
import { 
  Utensils, 
  Clock, 
  RotateCw, 
  BrainCircuit, 
  ArrowRight,
  SlidersHorizontal,
  Calendar
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import MedicalDisclaimer from '../components/MedicalDisclaimer';
import AIPulse from '../components/AIPulse';

export const GeneratePlanPage: React.FC = () => {
  const { plan, profile, generateNewPlan, setActiveTab } = useAuth();
  const [generating, setGenerating] = useState(false);

  const handleGenerate = async () => {
    setGenerating(true);
    await generateNewPlan();
    setGenerating(false);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-fade-in">
      
      {/* Header Banner */}
      <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200/80 shadow-soft-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div className="space-y-3 max-w-2xl">
          <AIPulse label="Generated by FitBuddy AI" size="md" />

          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            Your AI Fitness Plan
          </h1>
          <p className="text-slate-600 text-sm leading-relaxed font-normal">
            Personalized AI workout blueprint and macro-balanced nutritional guide engineered for goal: <strong className="text-emerald-600 font-bold">{profile?.goal || 'General Fitness'}</strong>.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row items-center gap-3 w-full md:w-auto">
          <button
            onClick={() => setActiveTab('profile')}
            className="w-full sm:w-auto px-4 py-3 rounded-2xl border border-slate-200/80 text-slate-700 hover:text-slate-900 font-bold text-xs flex items-center justify-center gap-2 hover:bg-slate-50 transition-colors"
          >
            <SlidersHorizontal className="w-4 h-4" />
            <span>Edit Profile</span>
          </button>
          
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="w-full sm:w-auto px-6 py-3.5 rounded-2xl bg-gradient-to-r from-blue-600 via-blue-600 to-emerald-500 text-white font-bold text-sm shadow-md shadow-blue-500/20 hover:scale-[1.02] transition-all flex items-center justify-center gap-2 disabled:opacity-50"
          >
            <RotateCw className={`w-4 h-4 ${generating ? 'animate-spin' : ''}`} />
            <span>{generating ? 'Synthesizing Plan...' : 'Regenerate AI Plan'}</span>
          </button>
        </div>
      </div>

      <MedicalDisclaimer />

      {/* Loading State */}
      {generating && (
        <div className="bg-white border border-slate-200 rounded-3xl p-12 text-center space-y-4 shadow-soft-sm animate-pulse">
          <div className="w-14 h-14 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center mx-auto">
            <BrainCircuit className="w-7 h-7 animate-spin" />
          </div>
          <h3 className="text-xl font-bold text-slate-900">Synthesizing AI Plan...</h3>
          <p className="text-sm text-slate-500">Gemini AI is crafting exercise selections based on your equipment and targets.</p>
        </div>
      )}

      {/* Plan Details */}
      {!generating && plan && (
        <div className="space-y-8">
          
          {/* TIMELINE-STYLE WEEKLY WORKOUT PLAN */}
          <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-soft-sm space-y-6">
            <div className="flex items-center justify-between pb-4 border-b border-slate-100">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center font-bold">
                  <Calendar className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900">Weekly Workout Timeline</h3>
                  <p className="text-xs text-slate-500">Structured daily routines, estimated duration, and exercise counts</p>
                </div>
              </div>

              <button
                onClick={() => setActiveTab('workout')}
                className="px-4 py-2 rounded-xl bg-blue-600 text-white font-bold text-xs hover:bg-blue-700 transition-colors flex items-center gap-1.5"
              >
                <span>Start Today's Workout</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>

            {/* Timeline Cards Grid */}
            <div className="space-y-4">
              {plan.workoutPlan?.map((dayItem, idx) => (
                <div 
                  key={idx}
                  className="bg-slate-50/80 rounded-2xl p-5 border border-slate-200/80 hover:border-blue-300 transition-all flex flex-col md:flex-row items-start md:items-center justify-between gap-4"
                >
                  <div className="flex items-start gap-4">
                    <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-blue-600 to-emerald-500 text-white font-extrabold text-xs flex items-center justify-center shrink-0 shadow-xs">
                      D{idx + 1}
                    </div>

                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className="font-extrabold text-base text-slate-900">{dayItem.day}</h4>
                        <span className="px-2.5 py-0.5 text-[10px] font-bold bg-white text-emerald-700 border border-slate-200 rounded-full">
                          Focus: {dayItem.focus}
                        </span>
                      </div>

                      <p className="text-xs text-slate-500 mt-1">
                        {dayItem.exercises?.length || 0} exercises prescribed • High efficiency rest intervals
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-3 text-xs font-bold w-full md:w-auto justify-between md:justify-end border-t md:border-t-0 pt-2 md:pt-0 border-slate-200">
                    <span className="px-3 py-1.5 rounded-xl bg-white border border-slate-200 text-slate-700 flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5 text-blue-600" />
                      {profile?.workoutDuration || 45} mins
                    </span>

                    <button
                      onClick={() => setActiveTab('workout')}
                      className="px-4 py-2 rounded-xl bg-white text-blue-600 border border-blue-200 hover:bg-blue-50 transition-colors"
                    >
                      View Day
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* SMART NUTRITION GUIDANCE */}
          <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-soft-sm space-y-6">
            <div className="flex items-center gap-3 pb-4 border-b border-slate-100">
              <div className="w-10 h-10 rounded-2xl bg-emerald-50 text-emerald-600 flex items-center justify-center font-bold">
                <Utensils className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-slate-900">Smart Nutrition Guidance</h3>
                <p className="text-xs text-slate-500">Macro-balanced meal suggestions and hydration target</p>
              </div>
            </div>

            {plan.nutritionPlan && (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
                <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200/80 space-y-1">
                  <span className="font-bold text-amber-600 uppercase tracking-wider block">Breakfast</span>
                  <p className="text-slate-800 font-medium">{plan.nutritionPlan.breakfast}</p>
                </div>

                <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200/80 space-y-1">
                  <span className="font-bold text-emerald-600 uppercase tracking-wider block">Lunch</span>
                  <p className="text-slate-800 font-medium">{plan.nutritionPlan.lunch}</p>
                </div>

                <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200/80 space-y-1">
                  <span className="font-bold text-blue-600 uppercase tracking-wider block">Dinner</span>
                  <p className="text-slate-800 font-medium">{plan.nutritionPlan.dinner}</p>
                </div>

                <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200/80 space-y-1">
                  <span className="font-bold text-purple-600 uppercase tracking-wider block">Snacks</span>
                  <p className="text-slate-800 font-medium">{plan.nutritionPlan.snacks}</p>
                </div>
              </div>
            )}
          </div>

        </div>
      )}

    </div>
  );
};

export default GeneratePlanPage;
